[aliases]
ll = "ls -alishF"
gogit = 'cd ~/git'
g = 'git'
gitalias = 'git config --get-regexp ^alias'
gac = 'git add . && git commit -m'
ghnoreply = "echo \"$(gh api user --jq '.id')+$(gh api user --jq '.login')@users.noreply.github.com\""
dp = "docker ps"
dpa = "docker ps -a"
dcub = "docker compose up --build"
dcd = "docker compose down"
dcdr = "docker compose down --remove-orphans"
system_docker_start = "sudo systemctl enable docker.service && sudo systemctl enable containerd.service"
system_docker_disable = "sudo systemctl disable docker.service && sudo systemctl disable containerd.service"
gr = "./gradlew"
help_screen = "echo 'screen cmd: ctrl + a, then d to detach. screen -r to resume. screen -ls to list.'"
windows_sleep = "rundll32.exe powrprof.dll,SetSuspendState 0,1,0"
setbashrc = "edit $HOME/.bashrc"

[exports]
EDITOR = "code"
GITHUB_TOKEN = "$(gh auth token)"

[metadata]
url_origin = "https://github.com/Fabbbou/my-duh"
name_origin = "my-duh"
